# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: golang:1.18

pipelines:
  branches:
    master:
      - step:
          name: Build and release
          script: # Modify the commands below to build your repository.
          - export CURRFOLDER=$(pwd)
          - BITBUCKET_REPO_FULL_NAME="wallix/awless"
          - PACKAGE_PATH="${GOPATH}/src/github.com/${BITBUCKET_REPO_FULL_NAME}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - go mod download
          - go get -v golang.org/x/net/proxy
          - go get -v || true
          - go get -v golang.org/x/net/proxy
          - go get -u golang.org/x/tools/cmd/goimports
          - go generate gen/aws/generators/main.go
          - cd ${GOPATH}/src/golang.org/x/net/proxy && go get -u -v && cd -
          - go build -o acentera -v
          - cd ${PACKAGE_PATH}
          - cp -Rfp ${CURRFOLDER}/.git .
          - cp -Rfp ${CURRFOLDER}/release.sh .
          - git remote add github-origin https://${GITHUB_TOKEN}@github.com/ACenterA/acenteracli.git
          - git push -u github-origin master
          - apt-get update && apt-get -y install zip
          - sh release.sh

